# Generated by Django 3.2.5 on 2021-07-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('model_name', models.CharField(max_length=300, verbose_name='model_name')),
                ('model_path', models.CharField(max_length=300, verbose_name='model_path')),
                ('config_path', models.CharField(max_length=300, verbose_name='config_path')),
            ],
            options={
                'db_table': 'predict_model',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('input_image_path', models.CharField(max_length=300, verbose_name='input_image_path')),
                ('predict_image_path', models.CharField(max_length=300, verbose_name='predict_image_path')),
                ('predict_json_path', models.CharField(max_length=300, verbose_name='predict_json_path')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
